baseURL = "https://jannekem.github.io/hugo-zettel/"
languageCode = "en-us"
title = "Hugo Zettel"

theme = "hugo-zettel"
pluralizelisttitles = false
canonifyURLs = true

[params]
    cardContentLength = 500

[taxonomies]
    tag = "tags"
    link = "links"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4
