name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.69.2'
          extended: true
          
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          
      - name: Install global dependencies
        run: |
          npm install -g postcss-cli
          npm install -g autoprefixer
      
      - name: Install Node dependencies
        run: npm install

      - name: Build
        run: hugo --gc --minify -s exampleSite --themesDir=../..

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: exampleSite/public # The folder the action should deploy.
